# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 12:11
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '__first__'),
        ('group', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name=b'description')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('contest_type', models.IntegerField(choices=[(1, b'\xe5\x85\xac\xe5\xbc\x80\xe8\xb5\x9b'), (2, b'\xe7\xa7\x81\xe6\x9c\x89\xe8\xb5\x9b'), (3, b'\xe5\xb0\x8f\xe7\xbb\x84\xe8\xb5\x9b'), (4, b'\xe9\x82\x80\xe8\xaf\xb7\xe8\xb5\x9b-\xe5\xb0\x8f\xe7\xbb\x84'), (5, b'\xe9\x82\x80\xe8\xaf\xb7\xe8\xb5\x9b-\xe4\xb8\xaa\xe4\xba\xba'), (6, b'\xe8\x80\x83\xe8\xaf\x95')])),
                ('password', models.CharField(blank=True, max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creat', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, to='group.Group')),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(blank=True, max_length=5)),
                ('all', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('problems_status', jsonfield.fields.JSONField(default={})),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
            options={
                'db_table': 'contest_problem',
            },
        ),
        migrations.CreateModel(
            name='ContestRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_status', jsonfield.fields.JSONField(default={})),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_rank',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(through='contest.ContestProblem', to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
